version: 2.1
description: pipeline tools for building Python apps

executors:
  python37:
    description: Executor for building Python based application
    docker:
      - image: python:3.7
  python37-postgres:
    description: Executor for building Python based application, along with a side PostgreSQL container for database integration tests
    docker:
      - image: python:3.7
      - image: cimg/postgres:14.0

jobs:
  test:
    description: Run tests and generate coverage report
    parameters:
      package_name:
        description: Python package name
        type: string
      test_path:
        description: Test path
        type: string
      install_requirements:
        description: Should install requirements
        type: boolean
        default: true
      pre_run_steps:
        description: List of steps to execute before running tests
        type: steps
        default: []
      run_directory:
        description: Directory to run commands in
        type: string
        default: "./"
      executor_type:
        description: The executor used for running the job
        type: executor
        default: python37
    executor: << parameters.executor_type >>
        environment:
          TEST_DATABASE_URL: $AWS_db_HOST
          POSTGRES_USER: terrybrooksjr
        auth:
          username: terrybrooksjr
          password: $AWS_db_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - steps: << parameters.pre_run_steps >>
      - when:
          condition: << parameters.install_requirements >>
          steps:
            - run:
                name: Install requirements
                command: |
                  cd << parameters.run_directory >>
                  pip3 install --upgrade pip
                  pip3 install --upgrade setuptools
                  pip3 install --upgrade -r requirements.txt
      - run: Install Postgres 

      - run:
          name: Install Coverage
          command: |
            cd << parameters.run_directory >>
            pip3 install coverage
      - run:
          name: Run tests
          command: |
            cd << parameters.run_directory >>
            pytest --cov=<< parameters.package_name >> << parameters.test_path >>