-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."PlatformUsers"
(
    user_id smallint NOT NULL DEFAULT nextval('"PlatformUsers_user_id_seq"'::regclass),
    username character varying(8)[] COLLATE pg_catalog."default" NOT NULL,
    user_first_name character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    user_last_name character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    daycare_facility smallint NOT NULL,
    role character varying(4)[] COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(32)[] COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_at timestamp with time zone,
    last_login timestamp without time zone[],
    CONSTRAINT "User ID" PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.daycare_location
(
    location_name character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    location_director character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    location_street_number smallint NOT NULL,
    location_street_name character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    locations_street_suffix character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    location_street_2_address character varying(255)[] COLLATE pg_catalog."default",
    location_city character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    location_state character varying(2)[] COLLATE pg_catalog."default" NOT NULL,
    location_postal_code smallint[] NOT NULL,
    opened_at date NOT NULL,
    closed_on date,
    location_id character varying(4)[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT daycare_location_pkey PRIMARY KEY (location_id)
);

ALTER TABLE IF EXISTS public."PlatformUsers"
    ADD FOREIGN KEY (daycare_facility)
    REFERENCES public.daycare_location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;